version: "3"
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    network_mode: "host"
    ports:
      - "8080:8080"
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices: 
      - "/dev/kmsg"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: "host"
    ports:
      - "9090:9090"
    volumes: 
      - ./prometheus:/etc/prometheus
    privileged: true
    depends_on:
      - cadvisor

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    network_mode: "host"
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - DS_PROMETHEUS=prometheus
    volumes: 
      - ./grafana:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/dashboards      # 添加 dashboards 映射
      - ./grafana/provisioning:/etc/grafana/provisioning  # 添加 provisioning 映射
    privileged: true
    depends_on:
      - prometheus

#volumes:
#  grafana-data: