version: "3"

networks:
  prometheus:
    driver: bridge

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - prometheus
  
  loki:
    image: grafana/loki:3.1.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml  # 修正配置檔名稱
    depends_on:
      - promtail
    networks:
      - prometheus
  
  promtail:
    image: grafana/promtail:3.1.2
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./data/promtail/log:/var/log
      - ./config/promtail:/etc/promtail
      - ./config/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      # Windows 環境下的容器日誌路徑
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - //./pipe/docker_engine://./pipe/docker_engine # 修正的 npipe 配置
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - prometheus
  
  node-exporter:
    image: prom/node-exporter:v1.9.0
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - "9100:9100"
    networks:
      - prometheus
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    #network_mode: "host"
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk
    privileged: true
    devices:
      - "/dev/kmsg"
    networks:
      - prometheus
  
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    #network_mode: "host"
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus
    privileged: true
    networks:
      - prometheus
  
  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    #network_mode: "host"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning  # 添加 provisioning 映射
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    privileged: true
    depends_on:
      - loki
      - prometheus
    networks:
      - prometheus 