tolgee:
  authentication:
    enabled: true
    initial-password: admin
    initial-username: admin
#    jwt-secret: my_jwt_secret
  machine-translation:
#    google:
#      api-key: my_google_api_key
    deepl:
      auth-key: my_deepl_api_key
  smtp:
    auth: true
    from: Tolgee <no-reply@mydomain.com>
    host: email-smtp.regional-region.amazonaws.com
    password: admin
    port: 465
    ssl-enabled: true
    username: user@company.com
  postgres-autostart:
    enabled: false
spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres