version: '3'

services:
  app:
    image: tolgee/tolgee:v3.83.3
    volumes:
      - ./data:/data
      - ./config.yaml:/config.yaml
    ports:
      - '8085:8080'
    environment:
      spring.config.additional-location: file:///config.yaml # <--- this line
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432' # <-- If you want to access your postgres from outside of docker network