auth_enabled: false

server:
  http_listen_port: 3100

querier:
  query_timeout: 1m
  engine:
    max_look_back_period: 0s

query_range:
  align_queries_with_step: true
  split_queries_by_interval: 15m
  max_retries: 5
  cache_results: true

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  tail_proxy_url: http://write-service:3100

schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  aws:
    s3: http://minio:9000
    bucketnames: loki
    access_key_id: minioadmin
    secret_access_key: minioadmin
  boltdb_shipper:
    active_index_directory: /loki/index
    shared_store: s3
    cache_location: /loki/cache

chunk_store_config:
  max_look_back_period: 0s

memberlist:
  join_members:
    - read-service
