//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace Lab.EF6.AlwaysEncrypt.UnitTest.Linq2DbEntityModel
{
	/// <summary>
	/// Database       : Lab.EF6.AlwaysEncrypt
	/// Data Source    : (localdb)\mssqllocaldb
	/// Server Version : 13.00.4001
	/// </summary>
	public partial class LabEF6AlwaysEncryptDB : LinqToDB.Data.DataConnection
	{
		public ITable<Employee> Employees { get { return this.GetTable<Employee>(); } }

		public LabEF6AlwaysEncryptDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public LabEF6AlwaysEncryptDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Employee")]
	public partial class Employee
	{
		[PrimaryKey, Identity   ] public int       Id       { get; set; } // int
		[Column,     NotNull    ] public string    Name     { get; set; } // nvarchar(10)
		[Column,        Nullable] public int?      Age      { get; set; } // int
		[Column,     NotNull    ] public DateTime  CreateAt { get; set; } // datetime
		[Column,        Nullable] public DateTime? ModifyAt { get; set; } // datetime
		[Column,        Nullable] public decimal?  Bonus    { get; set; } // numeric(3, 1)
	}

	public static partial class TableExtensions
	{
		public static Employee Find(this ITable<Employee> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
