// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace AuthSpike.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class 不中斷的正常輪替與洩漏撤銷Feature : object, global::Xunit.IClassFixture<不中斷的正常輪替與洩漏撤銷Feature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "不中斷的正常輪替與洩漏撤銷", "  依 08 單驗收項目，確認 mTLS 憑證與請求簽章金鑰可分開輪替；重疊期內新舊配置都能合法呼叫，\n  退役後舊配置不能通過；疑似洩漏時不等待重疊期結束，於 " +
                "60 秒內阻擋。\n  每 Client 每環境獨立配置私鑰。本 lab 不實作 Gateway，呼叫端直接呼叫業務 API。", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CredentialRotationAndLeakRevocation.feature"
#line hidden
        
        public 不中斷的正常輪替與洩漏撤銷Feature(不中斷的正常輪替與洩漏撤銷Feature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("授權伺服器與建立訂單 API 已啟動", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("已登錄服務 \"orders-client\" 與其用戶端憑證", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync("08 單的實作紀錄可讀取", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/CredentialRotationAndLeakRevocation.feature.ndjson", 15);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="輪替重疊期與操作程序已記錄於實作紀錄")]
        [global::Xunit.TraitAttribute("FeatureTitle", "不中斷的正常輪替與洩漏撤銷")]
        [global::Xunit.TraitAttribute("Description", "輪替重疊期與操作程序已記錄於實作紀錄")]
        public async global::System.Threading.Tasks.Task 輪替重疊期與操作程序已記錄於實作紀錄()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("輪替重疊期與操作程序已記錄於實作紀錄", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.ThenAsync("08 單第 1 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 13
    await testRunner.AndAsync("08 單的實作紀錄包含 \"重疊期\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
    await testRunner.AndAsync("08 單的實作紀錄包含 \"操作程序\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync("08 單的實作紀錄包含 \"lab 暫定、待使用者確認\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync("08 單的實作紀錄包含 \"mTLS 憑證與請求簽章金鑰分開管理\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="每 Client 每環境獨立配置私鑰")]
        [global::Xunit.TraitAttribute("FeatureTitle", "不中斷的正常輪替與洩漏撤銷")]
        [global::Xunit.TraitAttribute("Description", "每 Client 每環境獨立配置私鑰")]
        public async global::System.Threading.Tasks.Task 每Client每環境獨立配置私鑰()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("每 Client 每環境獨立配置私鑰", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.GivenAsync("另一個環境 \"production\" 的授權伺服器與建立訂單 API 已啟動", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
    await testRunner.ThenAsync("\"orders-client\" 在 \"lab\" 與 \"production\" 的 mTLS 憑證指紋互不相同", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 21
    await testRunner.AndAsync("\"orders-client\" 在 \"lab\" 與 \"production\" 的簽章金鑰識別與公開金鑰互不相同", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.AndAsync("\"orders-client\" 與 \"orders-partner-client\" 的簽章金鑰識別互不相同", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
    await testRunner.WhenAsync("呼叫端以 \"production\" 環境的 mTLS 憑證向該環境授權伺服器要求 Token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
    await testRunner.AndAsync("呼叫端以 \"lab\" 環境的簽章金鑰送出建立訂單請求", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
    await testRunner.ThenAsync("輪替情境的建立訂單回應為 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
    await testRunner.AndAsync("08 單第 2 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="正常輪替依登錄新 mTLS 憑證、切換呼叫端、再退役舊憑證的順序進行")]
        [global::Xunit.TraitAttribute("FeatureTitle", "不中斷的正常輪替與洩漏撤銷")]
        [global::Xunit.TraitAttribute("Description", "正常輪替依登錄新 mTLS 憑證、切換呼叫端、再退役舊憑證的順序進行")]
        [global::Xunit.TraitAttribute("Category", "isolated")]
        public async global::System.Threading.Tasks.Task 正常輪替依登錄新MTLS憑證切換呼叫端再退役舊憑證的順序進行()
        {
            string[] tagsOfScenario = new string[] {
                    "isolated"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("正常輪替依登錄新 mTLS 憑證、切換呼叫端、再退役舊憑證的順序進行", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 30
    await testRunner.GivenAsync("輪替情境中簽章呼叫端 \"orders-client\" 以既有配置取得 Token 並成功建立訂單 \"憑證輪替前訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
    await testRunner.WhenAsync("管理者嘗試在未登錄替代時退役 \"orders-client\" 的既有 \"mTLS 憑證\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
    await testRunner.ThenAsync("退役被拒絕且原因為 \"必須先登錄替代的憑證\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 33
    await testRunner.WhenAsync("管理者為 \"orders-client\" 產生新的 \"mTLS 憑證\" 但尚未登錄", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
    await testRunner.AndAsync("呼叫端以尚未登錄的新 mTLS 憑證向授權伺服器要求 Token", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
    await testRunner.ThenAsync("輪替情境的 Token 要求未核發", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
    await testRunner.WhenAsync("管理者登錄新產生的 \"mTLS 憑證\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
    await testRunner.AndAsync("呼叫端切換為新的 \"mTLS 憑證\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
    await testRunner.AndAsync("呼叫端以目前 mTLS 憑證向授權伺服器要求 Token", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
    await testRunner.ThenAsync("輪替情境的 Token 要求已核發", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 40
    await testRunner.WhenAsync("管理者退役 \"orders-client\" 的既有 \"mTLS 憑證\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
    await testRunner.ThenAsync("既有 \"mTLS 憑證\" 已列為退役", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
    await testRunner.AndAsync("08 單第 3 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="正常輪替依登錄新簽章金鑰、切換呼叫端、再退役舊金鑰的順序進行")]
        [global::Xunit.TraitAttribute("FeatureTitle", "不中斷的正常輪替與洩漏撤銷")]
        [global::Xunit.TraitAttribute("Description", "正常輪替依登錄新簽章金鑰、切換呼叫端、再退役舊金鑰的順序進行")]
        [global::Xunit.TraitAttribute("Category", "isolated")]
        public async global::System.Threading.Tasks.Task 正常輪替依登錄新簽章金鑰切換呼叫端再退役舊金鑰的順序進行()
        {
            string[] tagsOfScenario = new string[] {
                    "isolated"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("正常輪替依登錄新簽章金鑰、切換呼叫端、再退役舊金鑰的順序進行", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 46
    await testRunner.GivenAsync("輪替情境中簽章呼叫端 \"orders-client\" 以既有配置取得 Token 並成功建立訂單 \"金鑰輪替前訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
    await testRunner.WhenAsync("管理者嘗試在未登錄替代時退役 \"orders-client\" 的既有 \"簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
    await testRunner.ThenAsync("退役被拒絕且原因為 \"必須先登錄替代的金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 49
    await testRunner.WhenAsync("管理者為 \"orders-client\" 產生新的 \"簽章金鑰\" 但尚未登錄", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
    await testRunner.AndAsync("呼叫端以尚未登錄的新簽章金鑰送出查詢訂單 \"金鑰輪替前訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
    await testRunner.ThenAsync("輪替情境的查詢回應為 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 52
    await testRunner.WhenAsync("管理者登錄新產生的 \"簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
    await testRunner.AndAsync("呼叫端切換為新的 \"簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
    await testRunner.AndAsync("呼叫端以目前配置查詢訂單 \"金鑰輪替前訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
    await testRunner.ThenAsync("輪替情境的查詢回應為 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 56
    await testRunner.WhenAsync("管理者退役 \"orders-client\" 的既有 \"簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.ThenAsync("既有 \"簽章金鑰\" 已列為退役", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 58
    await testRunner.AndAsync("08 單第 3 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="重疊期內新舊配置都能合法呼叫，退役後舊配置不能通過")]
        [global::Xunit.TraitAttribute("FeatureTitle", "不中斷的正常輪替與洩漏撤銷")]
        [global::Xunit.TraitAttribute("Description", "重疊期內新舊配置都能合法呼叫，退役後舊配置不能通過")]
        [global::Xunit.TraitAttribute("Category", "isolated")]
        public async global::System.Threading.Tasks.Task 重疊期內新舊配置都能合法呼叫退役後舊配置不能通過()
        {
            string[] tagsOfScenario = new string[] {
                    "isolated"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("重疊期內新舊配置都能合法呼叫，退役後舊配置不能通過", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 62
    await testRunner.GivenAsync("輪替情境中簽章呼叫端 \"orders-client\" 以既有配置取得 Token 並成功建立訂單 \"舊配置訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 63
    await testRunner.WhenAsync("管理者為 \"orders-client\" 產生並登錄新的 \"mTLS 憑證與簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
    await testRunner.AndAsync("呼叫端切換為新的 \"mTLS 憑證與簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
    await testRunner.AndAsync("呼叫端以目前 mTLS 憑證向授權伺服器要求 Token", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
    await testRunner.AndAsync("呼叫端以目前配置建立訂單 \"新配置訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
    await testRunner.ThenAsync("輪替情境的建立訂單回應為 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 68
    await testRunner.WhenAsync("呼叫端以既有配置查詢訂單 \"舊配置訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
    await testRunner.ThenAsync("輪替情境的查詢回應為 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 70
    await testRunner.WhenAsync("管理者退役 \"orders-client\" 的既有 \"mTLS 憑證與簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
    await testRunner.ThenAsync("既有 \"mTLS 憑證與簽章金鑰\" 已列為退役", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
    await testRunner.WhenAsync("呼叫端以既有配置查詢訂單 \"舊配置訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
    await testRunner.ThenAsync("輪替情境的查詢回應為 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 74
    await testRunner.WhenAsync("呼叫端以既有配置向授權伺服器要求 Token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 75
    await testRunner.ThenAsync("輪替情境的 Token 要求被拒絕", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 76
    await testRunner.WhenAsync("呼叫端以目前配置查詢訂單 \"新配置訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 77
    await testRunner.ThenAsync("輪替情境的查詢回應為 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 78
    await testRunner.AndAsync("08 單第 4 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="新憑證取得綁定自己的 Token，舊 Token 搭配新憑證被拒絕")]
        [global::Xunit.TraitAttribute("FeatureTitle", "不中斷的正常輪替與洩漏撤銷")]
        [global::Xunit.TraitAttribute("Description", "新憑證取得綁定自己的 Token，舊 Token 搭配新憑證被拒絕")]
        [global::Xunit.TraitAttribute("Category", "isolated")]
        public async global::System.Threading.Tasks.Task 新憑證取得綁定自己的Token舊Token搭配新憑證被拒絕()
        {
            string[] tagsOfScenario = new string[] {
                    "isolated"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("新憑證取得綁定自己的 Token，舊 Token 搭配新憑證被拒絕", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 81
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 82
    await testRunner.GivenAsync("輪替情境中簽章呼叫端 \"orders-client\" 以既有配置取得 Token 並成功建立訂單 \"舊 Token 訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 83
    await testRunner.WhenAsync("管理者為 \"orders-client\" 產生並登錄新的 \"mTLS 憑證與簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
    await testRunner.AndAsync("呼叫端切換為新的 \"mTLS 憑證與簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
    await testRunner.AndAsync("呼叫端以既有 Token 搭配目前配置查詢訂單 \"舊 Token 訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
    await testRunner.ThenAsync("輪替情境的查詢回應為 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 87
    await testRunner.WhenAsync("呼叫端以目前 mTLS 憑證向授權伺服器要求 Token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 88
    await testRunner.ThenAsync("輪替情境的 Token 要求已核發", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 89
    await testRunner.WhenAsync("呼叫端以目前配置建立訂單 \"新 Token 訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 90
    await testRunner.ThenAsync("輪替情境的建立訂單回應為 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 91
    await testRunner.AndAsync("08 單第 5 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="只輪替 mTLS 憑證時簽章金鑰狀態不被連動")]
        [global::Xunit.TraitAttribute("FeatureTitle", "不中斷的正常輪替與洩漏撤銷")]
        [global::Xunit.TraitAttribute("Description", "只輪替 mTLS 憑證時簽章金鑰狀態不被連動")]
        [global::Xunit.TraitAttribute("Category", "isolated")]
        public async global::System.Threading.Tasks.Task 只輪替MTLS憑證時簽章金鑰狀態不被連動()
        {
            string[] tagsOfScenario = new string[] {
                    "isolated"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("只輪替 mTLS 憑證時簽章金鑰狀態不被連動", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 94
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 95
    await testRunner.GivenAsync("輪替情境中簽章呼叫端 \"orders-client\" 以既有配置取得 Token 並成功建立訂單 \"分開輪替訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 96
    await testRunner.WhenAsync("管理者為 \"orders-client\" 產生並登錄新的 \"mTLS 憑證\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 97
    await testRunner.AndAsync("呼叫端切換為新的 \"mTLS 憑證\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
    await testRunner.AndAsync("呼叫端以目前 mTLS 憑證向授權伺服器要求 Token", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
    await testRunner.AndAsync("呼叫端以目前配置建立訂單 \"新 mTLS 訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 100
    await testRunner.ThenAsync("輪替情境的建立訂單回應為 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 101
    await testRunner.AndAsync("既有 \"簽章金鑰\" 仍未列為退役", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 102
    await testRunner.WhenAsync("管理者退役 \"orders-client\" 的既有 \"mTLS 憑證\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 103
    await testRunner.ThenAsync("既有 \"mTLS 憑證\" 已列為退役", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 104
    await testRunner.WhenAsync("呼叫端以目前配置查詢訂單 \"分開輪替訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 105
    await testRunner.ThenAsync("輪替情境的查詢回應為 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 106
    await testRunner.WhenAsync("呼叫端以既有配置查詢訂單 \"分開輪替訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 107
    await testRunner.ThenAsync("輪替情境的查詢回應為 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 108
    await testRunner.AndAsync("08 單第 6 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="只輪替簽章金鑰時 mTLS 憑證狀態不被連動")]
        [global::Xunit.TraitAttribute("FeatureTitle", "不中斷的正常輪替與洩漏撤銷")]
        [global::Xunit.TraitAttribute("Description", "只輪替簽章金鑰時 mTLS 憑證狀態不被連動")]
        [global::Xunit.TraitAttribute("Category", "isolated")]
        public async global::System.Threading.Tasks.Task 只輪替簽章金鑰時MTLS憑證狀態不被連動()
        {
            string[] tagsOfScenario = new string[] {
                    "isolated"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("只輪替簽章金鑰時 mTLS 憑證狀態不被連動", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 111
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 112
    await testRunner.GivenAsync("輪替情境中簽章呼叫端 \"orders-client\" 以既有配置取得 Token 並成功建立訂單 \"分開簽章訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 113
    await testRunner.WhenAsync("管理者為 \"orders-client\" 產生並登錄新的 \"簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 114
    await testRunner.AndAsync("呼叫端切換為新的 \"簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
    await testRunner.AndAsync("呼叫端以目前配置建立訂單 \"新簽章金鑰訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
    await testRunner.ThenAsync("輪替情境的建立訂單回應為 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 117
    await testRunner.AndAsync("既有 \"mTLS 憑證\" 仍未列為退役", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
    await testRunner.WhenAsync("管理者退役 \"orders-client\" 的既有 \"簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 119
    await testRunner.ThenAsync("既有 \"簽章金鑰\" 已列為退役", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 120
    await testRunner.WhenAsync("呼叫端以既有配置查詢訂單 \"分開簽章訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 121
    await testRunner.ThenAsync("輪替情境的查詢回應為 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 122
    await testRunner.WhenAsync("呼叫端以目前配置查詢訂單 \"分開簽章訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 123
    await testRunner.ThenAsync("輪替情境的查詢回應為 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 124
    await testRunner.WhenAsync("呼叫端以既有配置向授權伺服器要求 Token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 125
    await testRunner.ThenAsync("輪替情境的 Token 要求已核發", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 126
    await testRunner.AndAsync("08 單第 6 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="重疊期內疑似洩漏時直接撤銷<對象>，既有配置於 60 秒內被阻擋")]
        [global::Xunit.TraitAttribute("FeatureTitle", "不中斷的正常輪替與洩漏撤銷")]
        [global::Xunit.TraitAttribute("Description", "重疊期內疑似洩漏時直接撤銷<對象>，既有配置於 60 秒內被阻擋")]
        [global::Xunit.TraitAttribute("Category", "isolated")]
        [global::Xunit.InlineDataAttribute("既有 mTLS 憑證", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("既有簽章金鑰", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("既有 Token", "10", new string[0])]
        public async global::System.Threading.Tasks.Task 重疊期內疑似洩漏時直接撤銷對象既有配置於60秒內被阻擋(string 對象, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "isolated"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("對象", 對象);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("重疊期內疑似洩漏時直接撤銷<對象>，既有配置於 60 秒內被阻擋", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 129
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 130
    await testRunner.GivenAsync("輪替情境中簽章呼叫端 \"orders-client\" 以既有配置取得 Token 並成功建立訂單 \"洩漏前訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 131
    await testRunner.WhenAsync("管理者為 \"orders-client\" 產生並登錄新的 \"mTLS 憑證與簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 132
    await testRunner.AndAsync("呼叫端切換為新的 \"mTLS 憑證與簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 133
    await testRunner.AndAsync("呼叫端以目前 mTLS 憑證向授權伺服器要求 Token", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
    await testRunner.ThenAsync("既有配置尚未退役", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 135
    await testRunner.WhenAsync(string.Format("疑似洩漏時撤銷 \"{0}\"", 對象), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 136
    await testRunner.ThenAsync("既有配置的查詢於 60 秒內回應 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 137
    await testRunner.AndAsync("目前配置的查詢仍回應 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 138
    await testRunner.AndAsync("08 單第 7 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="重疊期內停用 Client 時新舊配置都於 60 秒內被阻擋")]
        [global::Xunit.TraitAttribute("FeatureTitle", "不中斷的正常輪替與洩漏撤銷")]
        [global::Xunit.TraitAttribute("Description", "重疊期內停用 Client 時新舊配置都於 60 秒內被阻擋")]
        [global::Xunit.TraitAttribute("Category", "isolated")]
        public async global::System.Threading.Tasks.Task 重疊期內停用Client時新舊配置都於60秒內被阻擋()
        {
            string[] tagsOfScenario = new string[] {
                    "isolated"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("重疊期內停用 Client 時新舊配置都於 60 秒內被阻擋", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 147
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 148
    await testRunner.GivenAsync("輪替情境中簽章呼叫端 \"orders-client\" 以既有配置取得 Token 並成功建立訂單 \"停用前訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 149
    await testRunner.WhenAsync("管理者為 \"orders-client\" 產生並登錄新的 \"mTLS 憑證與簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 150
    await testRunner.AndAsync("呼叫端切換為新的 \"mTLS 憑證與簽章金鑰\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 151
    await testRunner.AndAsync("呼叫端以目前 mTLS 憑證向授權伺服器要求 Token", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 152
    await testRunner.AndAsync("疑似洩漏時撤銷 \"Client\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 153
    await testRunner.ThenAsync("既有配置的查詢於 60 秒內回應 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 154
    await testRunner.AndAsync("目前配置的查詢於 60 秒內回應 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 155
    await testRunner.AndAsync("08 單第 7 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="輪替與洩漏處理說明可重現且文件不含真實憑證或私鑰")]
        [global::Xunit.TraitAttribute("FeatureTitle", "不中斷的正常輪替與洩漏撤銷")]
        [global::Xunit.TraitAttribute("Description", "輪替與洩漏處理說明可重現且文件不含真實憑證或私鑰")]
        public async global::System.Threading.Tasks.Task 輪替與洩漏處理說明可重現且文件不含真實憑證或私鑰()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("輪替與洩漏處理說明可重現且文件不含真實憑證或私鑰", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 157
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 158
    await testRunner.ThenAsync("08 單的實作紀錄包含 \"輪替步驟\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 159
    await testRunner.AndAsync("08 單的實作紀錄包含 \"洩漏處理步驟\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 160
    await testRunner.AndAsync("08 單的實作紀錄包含 \"dotnet test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 161
    await testRunner.AndAsync("08 單的實作紀錄不包含真實私鑰或憑證內容", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 162
    await testRunner.AndAsync("08 單第 8 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await 不中斷的正常輪替與洩漏撤銷Feature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await 不中斷的正常輪替與洩漏撤銷Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
