// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace AuthSpike.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class 管理者撤銷與查證故障時拒絕處理Feature : object, global::Xunit.IClassFixture<管理者撤銷與查證故障時拒絕處理Feature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "管理者撤銷與查證故障時拒絕處理", "  依 07 單驗收項目，確認撤銷 Client、Token、mTLS 憑證或簽章金鑰後，各驗證端於 60 秒內阻擋後續請求；\n  查證服務故障且沒有時效內有效快" +
                "取時 fail closed，明確回報 503 且不進入業務副作用。\n  撤銷不回滾已提交的業務操作。本 lab 不實作 Gateway，呼叫端直接呼叫業務 A" +
                "PI。", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "RevocationAndFailClosed.feature"
#line hidden
        
        public 管理者撤銷與查證故障時拒絕處理Feature(管理者撤銷與查證故障時拒絕處理Feature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("授權伺服器與建立訂單 API 已啟動", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("已登錄服務 \"orders-client\" 與其用戶端憑證", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync("07 單的實作紀錄可讀取", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/RevocationAndFailClosed.feature.ndjson", 16);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="撤銷操作、狀態同步、快取與故障回應契約已記錄")]
        [global::Xunit.TraitAttribute("FeatureTitle", "管理者撤銷與查證故障時拒絕處理")]
        [global::Xunit.TraitAttribute("Description", "撤銷操作、狀態同步、快取與故障回應契約已記錄")]
        public async global::System.Threading.Tasks.Task 撤銷操作狀態同步快取與故障回應契約已記錄()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("撤銷操作、狀態同步、快取與故障回應契約已記錄", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.ThenAsync("07 單第 1 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 13
    await testRunner.AndAsync("07 單的實作紀錄包含 \"撤銷契約\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
    await testRunner.AndAsync("07 單的實作紀錄包含 \"查證快取\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync("07 單的實作紀錄包含 \"不新增管理 UI\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync("07 單的 API 契約包含 \"verification_unavailable\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="撤銷<對象>後後續請求在 60 秒內被阻擋")]
        [global::Xunit.TraitAttribute("FeatureTitle", "管理者撤銷與查證故障時拒絕處理")]
        [global::Xunit.TraitAttribute("Description", "撤銷<對象>後後續請求在 60 秒內被阻擋")]
        [global::Xunit.TraitAttribute("Category", "isolated")]
        [global::Xunit.InlineDataAttribute("Token", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("Client", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("mTLS 憑證", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("簽章金鑰", "4", new string[0])]
        public async global::System.Threading.Tasks.Task 撤銷對象後後續請求在60秒內被阻擋(string 對象, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "isolated"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("對象", 對象);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("撤銷<對象>後後續請求在 60 秒內被阻擋", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 20
    await testRunner.GivenAsync("簽章呼叫端 \"orders-client\" 以 mTLS 取得 Token 並成功建立訂單 \"撤銷前訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
    await testRunner.AndAsync("簽章呼叫端 \"orders-client\" 的查詢請求回應 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.WhenAsync(string.Format("管理者撤銷 \"{0}\"", 對象), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
    await testRunner.ThenAsync("撤銷後的查詢請求於 60 秒內回應 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 24
    await testRunner.AndAsync("07 單第 2 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="撤銷<對象>後既有 Token 仍為有效，但接受判斷仍拒絕")]
        [global::Xunit.TraitAttribute("FeatureTitle", "管理者撤銷與查證故障時拒絕處理")]
        [global::Xunit.TraitAttribute("Description", "撤銷<對象>後既有 Token 仍為有效，但接受判斷仍拒絕")]
        [global::Xunit.TraitAttribute("Category", "isolated")]
        [global::Xunit.InlineDataAttribute("Client", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("mTLS 憑證", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("簽章金鑰", "7", new string[0])]
        public async global::System.Threading.Tasks.Task 撤銷對象後既有Token仍為有效但接受判斷仍拒絕(string 對象, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "isolated"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("對象", 對象);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("撤銷<對象>後既有 Token 仍為有效，但接受判斷仍拒絕", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 35
    await testRunner.GivenAsync("簽章呼叫端 \"orders-client\" 以 mTLS 取得 Token 並成功建立訂單 \"撤銷前訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
    await testRunner.WhenAsync(string.Format("管理者撤銷 \"{0}\"", 對象), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
    await testRunner.ThenAsync("授權伺服器對既有 Token 的 introspection 仍為 active", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 38
    await testRunner.AndAsync("撤銷後的查詢請求於 60 秒內回應 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
    await testRunner.AndAsync("07 單第 5 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="撤銷 Token 後兩個執行個體於 60 秒內拒絕後續請求")]
        [global::Xunit.TraitAttribute("FeatureTitle", "管理者撤銷與查證故障時拒絕處理")]
        [global::Xunit.TraitAttribute("Description", "撤銷 Token 後兩個執行個體於 60 秒內拒絕後續請求")]
        [global::Xunit.TraitAttribute("Category", "isolated")]
        public async global::System.Threading.Tasks.Task 撤銷Token後兩個執行個體於60秒內拒絕後續請求()
        {
            string[] tagsOfScenario = new string[] {
                    "isolated"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("撤銷 Token 後兩個執行個體於 60 秒內拒絕後續請求", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 49
    await testRunner.GivenAsync("第二個建立訂單 API 執行個體已啟動並共用防重放儲存", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 50
    await testRunner.AndAsync("簽章呼叫端 \"orders-client\" 以 mTLS 取得 Token 並成功建立訂單 \"多執行個體訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
    await testRunner.AndAsync("簽章呼叫端 \"orders-client\" 的查詢請求於第二個執行個體回應 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
    await testRunner.WhenAsync("管理者撤銷 \"Token\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
    await testRunner.ThenAsync("撤銷後的查詢請求於 60 秒內回應 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
    await testRunner.AndAsync("第二個執行個體的撤銷後查詢於 60 秒內回應 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
    await testRunner.AndAsync("07 單第 3 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="既有連線與第二個執行個體上的後續請求同樣被阻擋")]
        [global::Xunit.TraitAttribute("FeatureTitle", "管理者撤銷與查證故障時拒絕處理")]
        [global::Xunit.TraitAttribute("Description", "既有連線與第二個執行個體上的後續請求同樣被阻擋")]
        [global::Xunit.TraitAttribute("Category", "isolated")]
        public async global::System.Threading.Tasks.Task 既有連線與第二個執行個體上的後續請求同樣被阻擋()
        {
            string[] tagsOfScenario = new string[] {
                    "isolated"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("既有連線與第二個執行個體上的後續請求同樣被阻擋", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 58
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 59
    await testRunner.GivenAsync("第二個建立訂單 API 執行個體已啟動並共用防重放儲存", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
    await testRunner.AndAsync("簽章呼叫端 \"orders-client\" 以既有連線取得 Token 並成功建立訂單 \"連線訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
    await testRunner.AndAsync("簽章呼叫端 \"orders-client\" 的查詢請求於第二個執行個體回應 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
    await testRunner.WhenAsync("管理者撤銷 \"Token\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
    await testRunner.ThenAsync("撤銷後的查詢請求於 60 秒內回應 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 64
    await testRunner.AndAsync("後續查詢請求使用的連線與撤銷前相同", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
    await testRunner.AndAsync("第二個執行個體的撤銷後查詢於 60 秒內回應 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
    await testRunner.AndAsync("07 單第 4 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="60 秒門檻的測量起點與拒絕結果已記錄於實作紀錄")]
        [global::Xunit.TraitAttribute("FeatureTitle", "管理者撤銷與查證故障時拒絕處理")]
        [global::Xunit.TraitAttribute("Description", "60 秒門檻的測量起點與拒絕結果已記錄於實作紀錄")]
        public async global::System.Threading.Tasks.Task _60秒門檻的測量起點與拒絕結果已記錄於實作紀錄()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("60 秒門檻的測量起點與拒絕結果已記錄於實作紀錄", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 68
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 69
    await testRunner.ThenAsync("07 單的實作紀錄包含 \"測量起點\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 70
    await testRunner.AndAsync("07 單的實作紀錄包含 \"拒絕時間\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
    await testRunner.AndAsync("07 單的實作紀錄包含 \"60 秒門檻\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
    await testRunner.AndAsync("07 單第 9 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="查證服務故障時快取有效期間內可接受，且失敗不延長快取有效期限")]
        [global::Xunit.TraitAttribute("FeatureTitle", "管理者撤銷與查證故障時拒絕處理")]
        [global::Xunit.TraitAttribute("Description", "查證服務故障時快取有效期間內可接受，且失敗不延長快取有效期限")]
        [global::Xunit.TraitAttribute("Category", "short-cache")]
        public async global::System.Threading.Tasks.Task 查證服務故障時快取有效期間內可接受且失敗不延長快取有效期限()
        {
            string[] tagsOfScenario = new string[] {
                    "short-cache"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("查證服務故障時快取有效期間內可接受，且失敗不延長快取有效期限", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 75
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 76
    await testRunner.GivenAsync("簽章呼叫端 \"orders-client\" 以 mTLS 取得 Token 並成功建立訂單 \"快取前訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 77
    await testRunner.AndAsync("授權伺服器停止服務", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
    await testRunner.WhenAsync("在快取有效期限內送出查詢請求", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
    await testRunner.ThenAsync("被快取允許的查詢回應為 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 80
    await testRunner.WhenAsync("等待查證快取過期後連續送出 2 次查詢請求", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
    await testRunner.ThenAsync("所有查詢回應為 503 且錯誤代碼為 \"verification_unavailable\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
    await testRunner.AndAsync("查詢回應不是憑證無效的 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
    await testRunner.AndAsync("07 單第 6 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
    await testRunner.AndAsync("07 單第 7 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="查證服務故障且沒有有效快取時拒絕處理且不建立訂單")]
        [global::Xunit.TraitAttribute("FeatureTitle", "管理者撤銷與查證故障時拒絕處理")]
        [global::Xunit.TraitAttribute("Description", "查證服務故障且沒有有效快取時拒絕處理且不建立訂單")]
        [global::Xunit.TraitAttribute("Category", "isolated")]
        public async global::System.Threading.Tasks.Task 查證服務故障且沒有有效快取時拒絕處理且不建立訂單()
        {
            string[] tagsOfScenario = new string[] {
                    "isolated"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("查證服務故障且沒有有效快取時拒絕處理且不建立訂單", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 87
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 88
    await testRunner.GivenAsync("簽章呼叫端 \"orders-client\" 以 mTLS 取得 Token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 89
    await testRunner.AndAsync("授權伺服器停止服務", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
    await testRunner.WhenAsync("授權伺服器停止後，簽章呼叫端 \"orders-client\" 以 Idempotency-Key \"outage-key\" 送出建立訂單請求", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 91
    await testRunner.ThenAsync("最後一次嘗試的回應為 503 且錯誤代碼為 \"verification_unavailable\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 92
    await testRunner.AndAsync("最後一次嘗試的回應不是憑證無效的 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
    await testRunner.AndAsync("業務 API 建立訂單數為 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
    await testRunner.AndAsync("07 單第 6 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
    await testRunner.AndAsync("07 單第 7 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="撤銷後被拒絕的寫入不建立訂單，撤銷不回滾已提交的訂單")]
        [global::Xunit.TraitAttribute("FeatureTitle", "管理者撤銷與查證故障時拒絕處理")]
        [global::Xunit.TraitAttribute("Description", "撤銷後被拒絕的寫入不建立訂單，撤銷不回滾已提交的訂單")]
        [global::Xunit.TraitAttribute("Category", "isolated")]
        public async global::System.Threading.Tasks.Task 撤銷後被拒絕的寫入不建立訂單撤銷不回滾已提交的訂單()
        {
            string[] tagsOfScenario = new string[] {
                    "isolated"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("撤銷後被拒絕的寫入不建立訂單，撤銷不回滾已提交的訂單", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 98
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 99
    await testRunner.GivenAsync("簽章呼叫端 \"orders-client\" 以 mTLS 取得 Token 並成功建立訂單 \"已提交訂單\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 100
    await testRunner.WhenAsync("管理者撤銷 \"Token\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 101
    await testRunner.ThenAsync("撤銷後的查詢請求於 60 秒內回應 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 102
    await testRunner.WhenAsync("簽章呼叫端 \"orders-client\" 以 Idempotency-Key \"after-revoke\" 送出建立訂單請求", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 103
    await testRunner.ThenAsync("最後一次嘗試的回應為 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 104
    await testRunner.AndAsync("業務 API 建立訂單數為 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 105
    await testRunner.AndAsync("重新以 mTLS 取得新 Token 後查詢 \"已提交訂單\" 的狀態仍為 \"active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
    await testRunner.AndAsync("07 單第 8 項驗收已勾選", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await 管理者撤銷與查證故障時拒絕處理Feature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await 管理者撤銷與查證故障時拒絕處理Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
