server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [ '__meta_docker_container_name' ]
        target_label: 'container'
      - source_labels: [ '__meta_docker_container_id' ]
        target_label: 'container_id'
      - source_labels: [ '__meta_docker_container_log_stream' ]
        target_label: 'stream'
      - action: replace
        target_label: job
        replacement: container-logs
    pipeline_stages:
      #- docker: { }
      - labels:
          job: container-logs
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: message
          format: "Input line: {{ .line }}"
 
  - job_name: api-log
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      # 只保留 container name 包含 api 的 log
      - source_labels: ['__meta_docker_container_name']
        #regex: '/?*api*'
        regex: '/?.*api.*'
        #regex: '/?labloki.*'
        action: keep
    pipeline_stages:
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: message
          format: "Input line: {{ .line }}"
      - json:
          expressions:
            RequestId: RequestId
            RequestPath: RequestPath
            StatusCode: StatusCode
      - labels:
          RequestId:
          RequestPath:
          StatusCode: