  stages:
    - build
    - test
  
  job1:
    stage: build
    script:
      - echo "This job runs in the build stage."
  
  last-job:
    stage: .post
    script:
      - echo "This job runs in the .post stage, after all other stages."
  
  job2:
    stage: test
    script:
      - echo "This job runs in the test stage."