version: '3.7'
services:
  hashicorp:
    image: hashicorp/vault:latest
    container_name: hashicorp
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK