version: '3.8'
name: myapp
services:
  app1:
    build:
      context: ./app1
    ports:
      - "8081:80" # 將容器的 80 端口映射到主機的 8081 端口

  app2:
    build:
      context: ./app2
    ports:
      - "8082:80" # 將容器的 80 端口映射到主機的 8082 端口
