using System.IO.Compression;
using System.Web;
using System.Web.Http.Controllers;
using System.Web.Http.Filters;

namespace Lab.Compress.Filters
{
    public class CompressContentAttribute : ActionFilterAttribute
    {
        public static void GZipEncodePage()
        {
            var Response = HttpContext.Current.Response;

            if (IsGZipSupported())
            {
                var AcceptEncoding = HttpContext.Current.Request.Headers["Accept-Encoding"];

                if (AcceptEncoding.Contains("deflate"))
                {
                    Response.Filter = new DeflateStream(Response.Filter,
                                                        CompressionMode.Compress);

                    Response.AppendHeader("Content-Encoding", "deflate");
                }
                else
                {
                    Response.Filter = new GZipStream(Response.Filter,
                                                     CompressionMode.Compress);

                    //Response.Headers.Remove("Content-Encoding");

                    Response.AppendHeader("Content-Encoding", "gzip");
                }
            }

            // Allow proxy servers to cache encoded and unencoded versions separately
            Response.AppendHeader("Vary", "Content-Encoding");
        }

        /// <summary>
        ///     Determines if GZip is supported
        /// </summary>
        /// <returns></returns>
        public static bool IsGZipSupported()
        {
            var AcceptEncoding = HttpContext.Current.Request.Headers["Accept-Encoding"];
            if (!string.IsNullOrEmpty(AcceptEncoding) &&
                (AcceptEncoding.Contains("gzip") || AcceptEncoding.Contains("deflate")))
            {
                return true;
            }

            return false;
        }

        /// <summary>
        ///     Override to compress the content that is generated by
        ///     an action method.
        /// </summary>
        /// <param name="filterContext"></param>
        public override void OnActionExecuting(HttpActionContext filterContext)
        {
            GZipEncodePage();
        }
    }

    ///// <summary>
    /////     强制Defalte压缩
    /////     Content-encoding:gzip，Content-Type:application/json
    /////     DEFLATE是一个无专利的压缩算法，它可以实现无损数据压缩，有众多开源的实现算法。
    ///// </summary>
    //public class DeflateCompressionAttribute : ActionFilterAttribute
    //{
    //    public override void OnActionExecuting(HttpActionContext filterContext)
    //    {
    //        var Response = HttpContext.Current.Response;
    //        Response.Filter = new DeflateStream(Response.Filter,
    //                                            CompressionMode.Compress);

    //        #region II6不支持此方法,(实际上此值默认为null 也不需要移除)

    //        //Response.Headers.Remove("Content-Encoding");

    //        #endregion

    //        Response.AppendHeader("Content-Encoding", "deflate");
    //    }
    //}

    ///// <summary>
    /////     强制GZip压缩，application/json
    /////     Content-encoding:gzip，Content-Type:application/json
    /////     GZIP是使用DEFLATE进行压缩数据的另一个压缩库
    ///// </summary>
    //public class GZipCompressionAttribute : ActionFilterAttribute
    //{
    //    public override void OnActionExecuting(HttpActionContext filterContext)
    //    {
    //        var Response = HttpContext.Current.Response;
    //        Response.Filter = new GZipStream(Response.Filter,
    //                                         CompressionMode.Compress);

    //        #region II6不支持此方法,(实际上此值默认为null 也不需要移除)

    //        //Response.Headers.Remove("Content-Encoding");

    //        #endregion

    //        Response.AppendHeader("Content-Encoding", "gzip");
    //    }
    //}
}