# Taskfile.yml

version: "3"

dotenv: [ "secrets/secrets.env" ]

tasks:
  webapi:
    desc: WebApi Development
    dir: "src/Lab.SerilogProject.WebApi"
    cmds:
      - dotnet run --environment Staging
  app:
    desc: WebApi Development
    dir: "src/Lab.SerilogProject.ConsoleApp"
    cmds:
      - dotnet run --environment Production
      
  seq-start:
    desc: start seq service
    cmds:
      - docker run --name seq -d --restart unless-stopped -e ACCEPT_EULA=Y -p 5341:80 datalust/seq:latest