# Taskfile.yml

version: "3"

dotenv: [ "secrets/secrets.env" ]

tasks:
  webapi:
    desc: WebApi Development
    dir: "src/Lab.SerilogProject.WebApi"
    cmds:
      - dotnet run --environment Staging
  app:
    desc: WebApi Development
    dir: "src/Lab.SerilogProject.ConsoleApp"
    cmds:
      - dotnet run --environment Production