CREATE TABLE [dbo].[Identity]
(
	[Employee_Id] UNIQUEIDENTIFIER  ENCRYPTED WITH (
	 COLUMN_ENCRYPTION_KEY = [yao],
	 ALGORITHM = N'AEAD_AES_256_CBC_HMAC_SHA_256',
	 ENCRYPTION_TYPE = DETERMINISTIC
	) NOT NULL PRIMARY KEY NONCLUSTERED, 
	[Account] NVARCHAR(50) NOT NULL, 
	[Password] NVARCHAR(50) NOT NULL, 
	CONSTRAINT [FK_Identity_To_Employee_Id] FOREIGN KEY ([Employee_Id]) REFERENCES [Employee]([Id])
	
)
