// <auto-generated />
using System;
using Lab.API.Signature.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lab.API.Signature.Migrations
{
    [DbContext(typeof(SignatureDbContext))]
    [Migration("20260921134359_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lab.API.Signature.Models.ApiKeyClient", b =>
                {
                    b.Property<string>("ApiKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ApiKey");

                    b.ToTable("ApiKeyClients", (string)null);

                    b.HasData(
                        new
                        {
                            ApiKey = "demo-api-key-001",
                            ClientName = "Demo Partner One",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Secret = "demo-secret-001-please-change"
                        },
                        new
                        {
                            ApiKey = "demo-api-key-002",
                            ClientName = "Demo Partner Two",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Secret = "demo-secret-002-please-change"
                        },
                        new
                        {
                            ApiKey = "demo-api-key-003",
                            ClientName = "Demo Partner Three",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Secret = "demo-secret-003-please-change"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
